# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /c/Users/perth/Documents/GitHub/ev3dev-cpp-wrapper-example

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /c/Users/perth/Documents/GitHub/ev3dev-cpp-wrapper-example

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /c/Users/perth/Documents/GitHub/ev3dev-cpp-wrapper-example/CMakeFiles /c/Users/perth/Documents/GitHub/ev3dev-cpp-wrapper-example//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /c/Users/perth/Documents/GitHub/ev3dev-cpp-wrapper-example/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aligned-terrance_EXECUTABLE

# Build rule for target.
aligned-terrance_EXECUTABLE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aligned-terrance_EXECUTABLE
.PHONY : aligned-terrance_EXECUTABLE

# fast build rule for target.
aligned-terrance_EXECUTABLE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aligned-terrance_EXECUTABLE.dir/build.make CMakeFiles/aligned-terrance_EXECUTABLE.dir/build
.PHONY : aligned-terrance_EXECUTABLE/fast

#=============================================================================
# Target rules for targets named aligned-terrance_TARGET

# Build rule for target.
aligned-terrance_TARGET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aligned-terrance_TARGET
.PHONY : aligned-terrance_TARGET

# fast build rule for target.
aligned-terrance_TARGET/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aligned-terrance_TARGET.dir/build.make CMakeFiles/aligned-terrance_TARGET.dir/build
.PHONY : aligned-terrance_TARGET/fast

#=============================================================================
# Target rules for targets named dumb-goalie-amogus_EXECUTABLE

# Build rule for target.
dumb-goalie-amogus_EXECUTABLE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dumb-goalie-amogus_EXECUTABLE
.PHONY : dumb-goalie-amogus_EXECUTABLE

# fast build rule for target.
dumb-goalie-amogus_EXECUTABLE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/build
.PHONY : dumb-goalie-amogus_EXECUTABLE/fast

#=============================================================================
# Target rules for targets named dumb-goalie-amogus_TARGET

# Build rule for target.
dumb-goalie-amogus_TARGET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dumb-goalie-amogus_TARGET
.PHONY : dumb-goalie-amogus_TARGET

# fast build rule for target.
dumb-goalie-amogus_TARGET/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumb-goalie-amogus_TARGET.dir/build.make CMakeFiles/dumb-goalie-amogus_TARGET.dir/build
.PHONY : dumb-goalie-amogus_TARGET/fast

#=============================================================================
# Target rules for targets named pppromaxattack_EXECUTABLE

# Build rule for target.
pppromaxattack_EXECUTABLE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pppromaxattack_EXECUTABLE
.PHONY : pppromaxattack_EXECUTABLE

# fast build rule for target.
pppromaxattack_EXECUTABLE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pppromaxattack_EXECUTABLE.dir/build.make CMakeFiles/pppromaxattack_EXECUTABLE.dir/build
.PHONY : pppromaxattack_EXECUTABLE/fast

#=============================================================================
# Target rules for targets named pppromaxattack_TARGET

# Build rule for target.
pppromaxattack_TARGET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pppromaxattack_TARGET
.PHONY : pppromaxattack_TARGET

# fast build rule for target.
pppromaxattack_TARGET/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pppromaxattack_TARGET.dir/build.make CMakeFiles/pppromaxattack_TARGET.dir/build
.PHONY : pppromaxattack_TARGET/fast

#=============================================================================
# Target rules for targets named quicktest_EXECUTABLE

# Build rule for target.
quicktest_EXECUTABLE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quicktest_EXECUTABLE
.PHONY : quicktest_EXECUTABLE

# fast build rule for target.
quicktest_EXECUTABLE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quicktest_EXECUTABLE.dir/build.make CMakeFiles/quicktest_EXECUTABLE.dir/build
.PHONY : quicktest_EXECUTABLE/fast

#=============================================================================
# Target rules for targets named quicktest_TARGET

# Build rule for target.
quicktest_TARGET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quicktest_TARGET
.PHONY : quicktest_TARGET

# fast build rule for target.
quicktest_TARGET/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quicktest_TARGET.dir/build.make CMakeFiles/quicktest_TARGET.dir/build
.PHONY : quicktest_TARGET/fast

#=============================================================================
# Target rules for targets named rickroll_EXECUTABLE

# Build rule for target.
rickroll_EXECUTABLE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rickroll_EXECUTABLE
.PHONY : rickroll_EXECUTABLE

# fast build rule for target.
rickroll_EXECUTABLE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rickroll_EXECUTABLE.dir/build.make CMakeFiles/rickroll_EXECUTABLE.dir/build
.PHONY : rickroll_EXECUTABLE/fast

#=============================================================================
# Target rules for targets named rickroll_TARGET

# Build rule for target.
rickroll_TARGET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rickroll_TARGET
.PHONY : rickroll_TARGET

# fast build rule for target.
rickroll_TARGET/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rickroll_TARGET.dir/build.make CMakeFiles/rickroll_TARGET.dir/build
.PHONY : rickroll_TARGET/fast

#=============================================================================
# Target rules for targets named slam-goalie-Terrance_EXECUTABLE

# Build rule for target.
slam-goalie-Terrance_EXECUTABLE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 slam-goalie-Terrance_EXECUTABLE
.PHONY : slam-goalie-Terrance_EXECUTABLE

# fast build rule for target.
slam-goalie-Terrance_EXECUTABLE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/build
.PHONY : slam-goalie-Terrance_EXECUTABLE/fast

#=============================================================================
# Target rules for targets named slam-goalie-Terrance_TARGET

# Build rule for target.
slam-goalie-Terrance_TARGET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 slam-goalie-Terrance_TARGET
.PHONY : slam-goalie-Terrance_TARGET

# fast build rule for target.
slam-goalie-Terrance_TARGET/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-Terrance_TARGET.dir/build.make CMakeFiles/slam-goalie-Terrance_TARGET.dir/build
.PHONY : slam-goalie-Terrance_TARGET/fast

#=============================================================================
# Target rules for targets named slam-goalie-amogus_EXECUTABLE

# Build rule for target.
slam-goalie-amogus_EXECUTABLE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 slam-goalie-amogus_EXECUTABLE
.PHONY : slam-goalie-amogus_EXECUTABLE

# fast build rule for target.
slam-goalie-amogus_EXECUTABLE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/build
.PHONY : slam-goalie-amogus_EXECUTABLE/fast

#=============================================================================
# Target rules for targets named slam-goalie-amogus_TARGET

# Build rule for target.
slam-goalie-amogus_TARGET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 slam-goalie-amogus_TARGET
.PHONY : slam-goalie-amogus_TARGET

# fast build rule for target.
slam-goalie-amogus_TARGET/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-amogus_TARGET.dir/build.make CMakeFiles/slam-goalie-amogus_TARGET.dir/build
.PHONY : slam-goalie-amogus_TARGET/fast

#=============================================================================
# Target rules for targets named ev3-cpp-template-wrapper-lib

# Build rule for target.
ev3-cpp-template-wrapper-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ev3-cpp-template-wrapper-lib
.PHONY : ev3-cpp-template-wrapper-lib

# fast build rule for target.
ev3-cpp-template-wrapper-lib/fast:
	$(MAKE) $(MAKESILENT) -f ev3dev-cpp-template-wrapper/bin/CMakeFiles/ev3-cpp-template-wrapper-lib.dir/build.make ev3dev-cpp-template-wrapper/bin/CMakeFiles/ev3-cpp-template-wrapper-lib.dir/build
.PHONY : ev3-cpp-template-wrapper-lib/fast

#=============================================================================
# Target rules for targets named EVERYTHING_BUILT_TARGET

# Build rule for target.
EVERYTHING_BUILT_TARGET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EVERYTHING_BUILT_TARGET
.PHONY : EVERYTHING_BUILT_TARGET

# fast build rule for target.
EVERYTHING_BUILT_TARGET/fast:
	$(MAKE) $(MAKESILENT) -f ev3dev-cpp-template-wrapper/bin/CMakeFiles/EVERYTHING_BUILT_TARGET.dir/build.make ev3dev-cpp-template-wrapper/bin/CMakeFiles/EVERYTHING_BUILT_TARGET.dir/build
.PHONY : EVERYTHING_BUILT_TARGET/fast

#=============================================================================
# Target rules for targets named LIB_BUILT_TARGET

# Build rule for target.
LIB_BUILT_TARGET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LIB_BUILT_TARGET
.PHONY : LIB_BUILT_TARGET

# fast build rule for target.
LIB_BUILT_TARGET/fast:
	$(MAKE) $(MAKESILENT) -f ev3dev-cpp-template-wrapper/bin/CMakeFiles/LIB_BUILT_TARGET.dir/build.make ev3dev-cpp-template-wrapper/bin/CMakeFiles/LIB_BUILT_TARGET.dir/build
.PHONY : LIB_BUILT_TARGET/fast

# target to build an object file
cmake_pch.hxx.gch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aligned-terrance_EXECUTABLE.dir/build.make CMakeFiles/aligned-terrance_EXECUTABLE.dir/cmake_pch.hxx.gch
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/cmake_pch.hxx.gch
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pppromaxattack_EXECUTABLE.dir/build.make CMakeFiles/pppromaxattack_EXECUTABLE.dir/cmake_pch.hxx.gch
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quicktest_EXECUTABLE.dir/build.make CMakeFiles/quicktest_EXECUTABLE.dir/cmake_pch.hxx.gch
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rickroll_EXECUTABLE.dir/build.make CMakeFiles/rickroll_EXECUTABLE.dir/cmake_pch.hxx.gch
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/cmake_pch.hxx.gch
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/cmake_pch.hxx.gch
.PHONY : cmake_pch.hxx.gch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aligned-terrance_EXECUTABLE.dir/build.make CMakeFiles/aligned-terrance_EXECUTABLE.dir/cmake_pch.hxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/cmake_pch.hxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pppromaxattack_EXECUTABLE.dir/build.make CMakeFiles/pppromaxattack_EXECUTABLE.dir/cmake_pch.hxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quicktest_EXECUTABLE.dir/build.make CMakeFiles/quicktest_EXECUTABLE.dir/cmake_pch.hxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rickroll_EXECUTABLE.dir/build.make CMakeFiles/rickroll_EXECUTABLE.dir/cmake_pch.hxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/cmake_pch.hxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aligned-terrance_EXECUTABLE.dir/build.make CMakeFiles/aligned-terrance_EXECUTABLE.dir/cmake_pch.hxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/cmake_pch.hxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pppromaxattack_EXECUTABLE.dir/build.make CMakeFiles/pppromaxattack_EXECUTABLE.dir/cmake_pch.hxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quicktest_EXECUTABLE.dir/build.make CMakeFiles/quicktest_EXECUTABLE.dir/cmake_pch.hxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rickroll_EXECUTABLE.dir/build.make CMakeFiles/rickroll_EXECUTABLE.dir/cmake_pch.hxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/cmake_pch.hxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

src/aligned-terrance.o: src/aligned-terrance.cpp.o
.PHONY : src/aligned-terrance.o

# target to build an object file
src/aligned-terrance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aligned-terrance_EXECUTABLE.dir/build.make CMakeFiles/aligned-terrance_EXECUTABLE.dir/src/aligned-terrance.cpp.o
.PHONY : src/aligned-terrance.cpp.o

src/aligned-terrance.i: src/aligned-terrance.cpp.i
.PHONY : src/aligned-terrance.i

# target to preprocess a source file
src/aligned-terrance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aligned-terrance_EXECUTABLE.dir/build.make CMakeFiles/aligned-terrance_EXECUTABLE.dir/src/aligned-terrance.cpp.i
.PHONY : src/aligned-terrance.cpp.i

src/aligned-terrance.s: src/aligned-terrance.cpp.s
.PHONY : src/aligned-terrance.s

# target to generate assembly for a file
src/aligned-terrance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aligned-terrance_EXECUTABLE.dir/build.make CMakeFiles/aligned-terrance_EXECUTABLE.dir/src/aligned-terrance.cpp.s
.PHONY : src/aligned-terrance.cpp.s

src/dumb-goalie-amogus.o: src/dumb-goalie-amogus.cpp.o
.PHONY : src/dumb-goalie-amogus.o

# target to build an object file
src/dumb-goalie-amogus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/src/dumb-goalie-amogus.cpp.o
.PHONY : src/dumb-goalie-amogus.cpp.o

src/dumb-goalie-amogus.i: src/dumb-goalie-amogus.cpp.i
.PHONY : src/dumb-goalie-amogus.i

# target to preprocess a source file
src/dumb-goalie-amogus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/src/dumb-goalie-amogus.cpp.i
.PHONY : src/dumb-goalie-amogus.cpp.i

src/dumb-goalie-amogus.s: src/dumb-goalie-amogus.cpp.s
.PHONY : src/dumb-goalie-amogus.s

# target to generate assembly for a file
src/dumb-goalie-amogus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/dumb-goalie-amogus_EXECUTABLE.dir/src/dumb-goalie-amogus.cpp.s
.PHONY : src/dumb-goalie-amogus.cpp.s

src/pppromaxattack.o: src/pppromaxattack.cpp.o
.PHONY : src/pppromaxattack.o

# target to build an object file
src/pppromaxattack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pppromaxattack_EXECUTABLE.dir/build.make CMakeFiles/pppromaxattack_EXECUTABLE.dir/src/pppromaxattack.cpp.o
.PHONY : src/pppromaxattack.cpp.o

src/pppromaxattack.i: src/pppromaxattack.cpp.i
.PHONY : src/pppromaxattack.i

# target to preprocess a source file
src/pppromaxattack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pppromaxattack_EXECUTABLE.dir/build.make CMakeFiles/pppromaxattack_EXECUTABLE.dir/src/pppromaxattack.cpp.i
.PHONY : src/pppromaxattack.cpp.i

src/pppromaxattack.s: src/pppromaxattack.cpp.s
.PHONY : src/pppromaxattack.s

# target to generate assembly for a file
src/pppromaxattack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pppromaxattack_EXECUTABLE.dir/build.make CMakeFiles/pppromaxattack_EXECUTABLE.dir/src/pppromaxattack.cpp.s
.PHONY : src/pppromaxattack.cpp.s

src/quicktest.o: src/quicktest.cpp.o
.PHONY : src/quicktest.o

# target to build an object file
src/quicktest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quicktest_EXECUTABLE.dir/build.make CMakeFiles/quicktest_EXECUTABLE.dir/src/quicktest.cpp.o
.PHONY : src/quicktest.cpp.o

src/quicktest.i: src/quicktest.cpp.i
.PHONY : src/quicktest.i

# target to preprocess a source file
src/quicktest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quicktest_EXECUTABLE.dir/build.make CMakeFiles/quicktest_EXECUTABLE.dir/src/quicktest.cpp.i
.PHONY : src/quicktest.cpp.i

src/quicktest.s: src/quicktest.cpp.s
.PHONY : src/quicktest.s

# target to generate assembly for a file
src/quicktest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quicktest_EXECUTABLE.dir/build.make CMakeFiles/quicktest_EXECUTABLE.dir/src/quicktest.cpp.s
.PHONY : src/quicktest.cpp.s

src/rickroll.o: src/rickroll.cpp.o
.PHONY : src/rickroll.o

# target to build an object file
src/rickroll.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rickroll_EXECUTABLE.dir/build.make CMakeFiles/rickroll_EXECUTABLE.dir/src/rickroll.cpp.o
.PHONY : src/rickroll.cpp.o

src/rickroll.i: src/rickroll.cpp.i
.PHONY : src/rickroll.i

# target to preprocess a source file
src/rickroll.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rickroll_EXECUTABLE.dir/build.make CMakeFiles/rickroll_EXECUTABLE.dir/src/rickroll.cpp.i
.PHONY : src/rickroll.cpp.i

src/rickroll.s: src/rickroll.cpp.s
.PHONY : src/rickroll.s

# target to generate assembly for a file
src/rickroll.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rickroll_EXECUTABLE.dir/build.make CMakeFiles/rickroll_EXECUTABLE.dir/src/rickroll.cpp.s
.PHONY : src/rickroll.cpp.s

src/slam-goalie-Terrance.o: src/slam-goalie-Terrance.cpp.o
.PHONY : src/slam-goalie-Terrance.o

# target to build an object file
src/slam-goalie-Terrance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/src/slam-goalie-Terrance.cpp.o
.PHONY : src/slam-goalie-Terrance.cpp.o

src/slam-goalie-Terrance.i: src/slam-goalie-Terrance.cpp.i
.PHONY : src/slam-goalie-Terrance.i

# target to preprocess a source file
src/slam-goalie-Terrance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/src/slam-goalie-Terrance.cpp.i
.PHONY : src/slam-goalie-Terrance.cpp.i

src/slam-goalie-Terrance.s: src/slam-goalie-Terrance.cpp.s
.PHONY : src/slam-goalie-Terrance.s

# target to generate assembly for a file
src/slam-goalie-Terrance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-Terrance_EXECUTABLE.dir/src/slam-goalie-Terrance.cpp.s
.PHONY : src/slam-goalie-Terrance.cpp.s

src/slam-goalie-amogus.o: src/slam-goalie-amogus.cpp.o
.PHONY : src/slam-goalie-amogus.o

# target to build an object file
src/slam-goalie-amogus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/src/slam-goalie-amogus.cpp.o
.PHONY : src/slam-goalie-amogus.cpp.o

src/slam-goalie-amogus.i: src/slam-goalie-amogus.cpp.i
.PHONY : src/slam-goalie-amogus.i

# target to preprocess a source file
src/slam-goalie-amogus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/src/slam-goalie-amogus.cpp.i
.PHONY : src/slam-goalie-amogus.cpp.i

src/slam-goalie-amogus.s: src/slam-goalie-amogus.cpp.s
.PHONY : src/slam-goalie-amogus.s

# target to generate assembly for a file
src/slam-goalie-amogus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/build.make CMakeFiles/slam-goalie-amogus_EXECUTABLE.dir/src/slam-goalie-amogus.cpp.s
.PHONY : src/slam-goalie-amogus.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... EVERYTHING_BUILT_TARGET"
	@echo "... LIB_BUILT_TARGET"
	@echo "... aligned-terrance_TARGET"
	@echo "... dumb-goalie-amogus_TARGET"
	@echo "... pppromaxattack_TARGET"
	@echo "... quicktest_TARGET"
	@echo "... rickroll_TARGET"
	@echo "... slam-goalie-Terrance_TARGET"
	@echo "... slam-goalie-amogus_TARGET"
	@echo "... aligned-terrance_EXECUTABLE"
	@echo "... dumb-goalie-amogus_EXECUTABLE"
	@echo "... ev3-cpp-template-wrapper-lib"
	@echo "... pppromaxattack_EXECUTABLE"
	@echo "... quicktest_EXECUTABLE"
	@echo "... rickroll_EXECUTABLE"
	@echo "... slam-goalie-Terrance_EXECUTABLE"
	@echo "... slam-goalie-amogus_EXECUTABLE"
	@echo "... cmake_pch.hxx.gch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
	@echo "... src/aligned-terrance.o"
	@echo "... src/aligned-terrance.i"
	@echo "... src/aligned-terrance.s"
	@echo "... src/dumb-goalie-amogus.o"
	@echo "... src/dumb-goalie-amogus.i"
	@echo "... src/dumb-goalie-amogus.s"
	@echo "... src/pppromaxattack.o"
	@echo "... src/pppromaxattack.i"
	@echo "... src/pppromaxattack.s"
	@echo "... src/quicktest.o"
	@echo "... src/quicktest.i"
	@echo "... src/quicktest.s"
	@echo "... src/rickroll.o"
	@echo "... src/rickroll.i"
	@echo "... src/rickroll.s"
	@echo "... src/slam-goalie-Terrance.o"
	@echo "... src/slam-goalie-Terrance.i"
	@echo "... src/slam-goalie-Terrance.s"
	@echo "... src/slam-goalie-amogus.o"
	@echo "... src/slam-goalie-amogus.i"
	@echo "... src/slam-goalie-amogus.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

