name: compile-test
on: [pull_request]
jobs:
  compile-out-of-container:
    runs-on: ubuntu-latest
    steps:
      #- name: install Docker
      #  run: |
      #    sudo apt-get update
      #    sudo apt install snap
      #    sudo snap install docker

      - name: Download this repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup docker images
        run: sudo bash ./ev3dev-cpp-template-wrapper/scripts/dockersetup.sh
      - name: compile the contents
        run: sudo bash ./scripts/compile.sh -w
  compile-inside-container:
    runs-on: ubuntu-latest
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    container: 
      image: eisverygoodletter/debian-stretch-cross:latest
      options: --user root -e GIT_DISCOVERY_ACROSS_FILESYSTEM=1
    steps:
      - name: install git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
      - uses: actions/checkout@v3
        with: 
          path: main
      - uses: actions/checkout@v3
        with:
          repository: rshs-robotics-club/ev3dev-cpp-template-wrapper
          path: main/ev3dev-cpp-template-wrapper
      - name: compile it
        run: |
          cd main
          sudo chmod +x ./scripts/runWithinContainer.sh
          sudo bash ./scripts/runWithinContainer.sh
        shell: bash
