name: compile-test
on: [pull_request]
jobs:
  compile-inside-container:
    runs-on: ubuntu-latest
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    container: 
      image: eisverygoodletter/debian-stretch-cross:latest
      options: --user root -e GIT_DISCOVERY_ACROSS_FILESYSTEM=1
    steps:
      - name: install git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
      - uses: actions/checkout@v3
        with: 
          path: ./
      - uses: actions/checkout@v3
        with:
          repository: rshs-robotics-club/ev3dev-cpp-template-wrapper
          path: ./ev3dev-cpp-template-wrapper
      - name: compile it
        run: |
          sudo chmod +x ./scripts/runWithinContainer.sh
          sudo bash ./scripts/runWithinContainer.sh -w
        shell: bash
